@host = 127.0.0.1
@port = 11000
@baseUrl = http://{{host}}:{{port}}/api/posts
#Test Request to JSON Placeholder
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Content-Type: application/json
###

############# GETTING POSTS LIST (Technical task, paragraph 3 ) #############
GET {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
###

GET {{baseUrl}}/?type=link HTTP/1.1
Content-Type: application/json
###

################################# DRAFTS #################################
GET {{baseUrl}}/drafts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ0NWNkMzZiM2I0YjkyMzQ0MWQ3ZWYiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsImZpcnN0bmFtZSI6IlRvbnkiLCJsYXN0bmFtZSI6IlN0YXJrIiwiaWF0IjoxNzE1Nzc4MjU1LCJleHAiOjE3MTU3Nzg1NTV9.nR4G8FBcqr0ZSjUQH1XkEG15dJLHhi3vcXMvxQEuKSE
###

################### SEARCH (Technical task, paragraph 8 ) ##################
GET {{baseUrl}}/search?title=inter&limit=19 HTTP/1.1
Content-Type: application/json
###

################################# GET DETAIL #################################
@detailPostId = b1cade4c-c6df-4fb8-8ae5-148a2cf52976
# Get detail info by post id
GET {{baseUrl}}/{{detailPostId}} HTTP/1.1
Content-Type: application/json
###

################################# CREATE #################################
# Create text-post
POST {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODY5Nzg2LCJleHAiOjE3MTU4NzAwODZ9.VJ4me4DZVNRwNcm8OJmjNxLABapbuSjwCsB4kPlRj8s

{
  "type": "text",
  "tags": ["test", "test", "news", "other"],
  "isPublished": true,
  "isRepost": false,
  "likes": [],
  "extraFields": {
    "announce": "Interesting text announce",
    "title": "Article title",
    "text": "Long story short text"
  }
}
###

################################# REPOST #################################
@repostingPostId = 3defd7fe-8566-41b5-9263-07f4548a3ead
POST {{baseUrl}}/{{repostingPostId}}/repost HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ0NWNkMzZiM2I0YjkyMzQ0MWQ3ZWYiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsImZpcnN0bmFtZSI6IlRvbnkiLCJsYXN0bmFtZSI6IlN0YXJrIiwiaWF0IjoxNzE1NzcxOTk4LCJleHAiOjE3MTU3NzIyOTh9.l69_gORNxrTYapoWBYzMSvaN9xn84pvPha7RxVuB_QQ
###

################################# UPDATING #################################
@updatingPostId = 2a618459-86e5-4521-8a59-8a84edf58707
PATCH  {{baseUrl}}/{{updatingPostId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcwMDc3LCJleHAiOjE3MTU4NzAzNzd9.udlG4im-6dyZUaRM0tV0JuQMljXkZtV0r9Ypw5Fpn2Y

{
  "isPublished": true
}
###

################################# DELETING #################################
@deletingPostId = 5bdcf353-a963-45d5-80d2-3785bbc05119
# Delete post by id
DELETE  {{baseUrl}}/{{deletingPostId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ0NWNkMzZiM2I0YjkyMzQ0MWQ3ZWYiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsImZpcnN0bmFtZSI6IlRvbnkiLCJsYXN0bmFtZSI6IlN0YXJrIiwiaWF0IjoxNzE1Nzc3NDQ3LCJleHAiOjE3MTU3Nzc3NDd9.BekA48-OWKiPQO3CG47Oy_JFTrt1lS2smIdmZrrPFsA
###



################################# COMMENTS #################################
# Create comment for post
@commentingPostId = b1cade4c-c6df-4fb8-8ae5-148a2cf52976
POST {{baseUrl}}/{{commentingPostId}}/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ0NWNkMzZiM2I0YjkyMzQ0MWQ3ZWYiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsImZpcnN0bmFtZSI6IlRvbnkiLCJsYXN0bmFtZSI6IlN0YXJrIiwiaWF0IjoxNzE1NzgxMzk1LCJleHAiOjE3MTU3ODE2OTV9.IEEt8ejOD9zYF7Anc60C3tLPB3rMIKvo1sbiXtOWcDg

{
  "text": "Some new comment"
}
###

# Get paginated comments
@postId = abdb5908-7ac4-467e-ab2a-76d11a5feeaf
GET {{baseUrl}}/{{postId}}/comments/?limit=5 HTTP/1.1
Content-Type: application/json
###

# Delete comment
@commentId = 7589eb0e-ca1d-42e8-8a8e-9faf196e9c23
DELETE {{baseUrl}}/{{commentingPostId}}/comments/{{commentId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ0NWNkMzZiM2I0YjkyMzQ0MWQ3ZWYiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsImZpcnN0bmFtZSI6IlRvbnkiLCJsYXN0bmFtZSI6IlN0YXJrIiwiaWF0IjoxNzE1NzgxMzk1LCJleHAiOjE3MTU3ODE2OTV9.IEEt8ejOD9zYF7Anc60C3tLPB3rMIKvo1sbiXtOWcDg
###



################################# USER POSTS FEED #################################
GET {{baseUrl}}/feed HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcwMDc3LCJleHAiOjE3MTU4NzAzNzd9.udlG4im-6dyZUaRM0tV0JuQMljXkZtV0r9Ypw5Fpn2Y
###
