@host = 127.0.0.1
@port = 11000
@baseUrl = http://{{host}}:{{port}}/api/users
#Test Request to JSON Placeholder
GET https://jsonplaceholder.typicode.com/todos/1 HTTP/1.1
Content-Type: application/json
###

////////////////////////////// AUTH //////////////////////////////
# Create new user
POST {{baseUrl}}/register/ HTTP/1.1
Content-Type: application/json

{
  "email": "iron-man333@starkindustries.it",
  "firstName": "Tony",
  "lastName": "Stark",
  "avatar": "/playboy/millioner/philanthropist.jpeg",
  "password": "jarvis-123"
}

###

# Login user 1
POST {{baseUrl}}/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "iron-man@starkindustries.it",
  "password": "jarvis-123"
}
###

# Login user 2
POST {{baseUrl}}/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "TEST-USER@starkindustries.it",
  "password": "jarvis-123"
}
###

# Change user password
PATCH {{baseUrl}}/password/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziIeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziIeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ0NWNkMzZiM2I0YjkyMzQ0MWQ3ZWYiLCJlbWFpbCI6Imlyb24tbWFuQHN0YXJraW5kdXN0cmllcy5pdCIsImZpcnN0bmFtZSI6IlRvbnkiLCJsYXN0bmFtZSI6IlN0YXJrIiwiaWF0IjoxNzE1NzU5NjIzLCJleHAiOjE3MTU3NTk5MjN9.l7hLLbZSkPwWktRBnlB145C2W5RAPHvtsPrAyuZPT68

{
  "password": "jarvis-123",
  "newPassword": "jarvis-1234"
}
###

# Refresh JWT Token (get new JWT pait: Token + Refresh-token)
GET {{baseUrl}}/refresh/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziIeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziIeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziI
###

////////////////////////////// USER //////////////////////////////
# Get detail info about user
POST {{baseUrl}}/detail/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziIeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziIeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziI
###

////////////////////////// SUBSCRIPTIONS //////////////////////
# Get user subscribers
GET {{baseUrl}}/subscribers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziI
###

# Subscribe user to target user
@targetUserId = 66445cd36b3b4b923441d7ef
POST {{baseUrl}}/subscribe/{{targetUserId}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziI
###

# Unsubscribe user to target user
POST {{baseUrl}}/unsubscribe/{{targetUserId}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ2MTc3NTI0YmE4ZGE3MDI0Njk2MmQiLCJlbWFpbCI6IlRFU1QtVVNFUkBzdGFya2luZHVzdHJpZXMuaXQiLCJmaXJzdG5hbWUiOiJURVNUIiwibGFzdG5hbWUiOiJURVNUIiwiaWF0IjoxNzE1ODcyMjYxLCJleHAiOjE3MTU4NzI1NjF9.Y51IkQPtZxbFDeTJyUg9P6tXhTDxJi0u7jSZjHoyziI
###

