# Server settings
@host = 127.0.0.1
@port = 8000
@baseUrl = http://{{host}}:{{port}}/api
# Environment
@userId = 6646177524ba8da70246962d
@targetUserId=66445cd36b3b4b923441d7ef
# @targetUserId=6643e89dc0e4066e5ba3d7c2
# @targetUserId=6643e8a1c0e4066e5ba3d7c5
# @targetUserId=6643e8a5c0e4066e5ba3d7c8

# Get detail info about user
POST {{baseUrl}}/users/ HTTP/1.1
Content-Type: application/json

{
  "userId": "6643e89dc0e4066e5ba3d7c2"
}
###

# Update user info
PATCH  {{baseUrl}}/users/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "firstName": "TT"
}
###

# Delete user
DELETE {{baseUrl}}/users/{{userId}} HTTP/1.1
###

# Change user password
PATCH {{baseUrl}}/users/{{userId}}/password/ HTTP/1.1
Content-Type: application/json

{
  "password": "jarvis-123",
  "newPassword": "123456"
}
###

# Add subscription
POST {{baseUrl}}/users/{{userId}}/subscribe/{{targetUserId}} HTTP/1.1
Content-Type: application/json
###

# Remove subscription
POST {{baseUrl}}/users/{{userId}}/unsubscribe/{{targetUserId}} HTTP/1.1
Content-Type: application/json
###

# Get user subscribers
GET {{baseUrl}}/users/{{userId}}/subscribers HTTP/1.1
Content-Type: application/json
###
